# Generated by Django 4.0.3 on 2022-04-13 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('envelope', models.ImageField(upload_to='photo/%Y/%m/%d', verbose_name='Обложка')),
                ('title', models.CharField(blank=True, default='Без названия', max_length=128, verbose_name='Название альбома')),
                ('date_album', models.DateField(auto_now_add=True, verbose_name='Дата релиза альбома')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Compozition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('envelope', models.ImageField(blank=True, upload_to='photo/%Y/%m/%d', verbose_name='Обложка')),
                ('title', models.CharField(blank=True, default='Без названия', max_length=455, verbose_name='Название')),
                ('file', models.FileField(upload_to='audio', verbose_name='Песня')),
                ('date_song', models.DateField(auto_now_add=True, null=True, verbose_name='Дата релиза песни')),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='musiccloud.album', verbose_name='Альбом')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='photo/%Y/%m/%d', verbose_name='Фото')),
                ('location', models.CharField(blank=True, max_length=30, verbose_name='Местоположение')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('about', models.TextField(blank=True, verbose_name='О себе')),
                ('nickname', models.CharField(max_length=128, null=True, verbose_name='Исполнитель')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Имя пользователя')),
            ],
        ),
        migrations.CreateModel(
            name='Playlists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Название Плейлиста')),
                ('envelope', models.ImageField(upload_to='photo/%Y/%m/%d', verbose_name='Обложка плейлиста')),
                ('date_playlist', models.DateField(auto_now_add=True, verbose_name='Дата создания плейлиста')),
                ('song', models.ManyToManyField(blank=True, to='musiccloud.compozition', verbose_name='Песня')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
