# Generated by Django 4.0.3 on 2022-04-13 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musiccloud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compozition',
            name='singer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='musiccloud.profile', verbose_name='Исполнитель'),
        ),
    ]
