# Generated by Django 4.0.3 on 2022-04-13 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musiccloud', '0002_compozition_singer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compozition',
            name='envelope',
            field=models.ImageField(blank=True, null=True, upload_to='photo/%Y/%m/%d', verbose_name='Обложка'),
        ),
    ]
