# Generated by Django 4.0.3 on 2022-04-14 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('musiccloud', '0003_alter_compozition_envelope'),
    ]

    operations = [
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('composition_envelope', models.ImageField(blank=True, null=True, upload_to='photo/%Y/%m/%d', verbose_name='Envelope')),
                ('composition_title', models.CharField(blank=True, default='Без названия', max_length=455, verbose_name='Title')),
                ('composition_file', models.FileField(upload_to='audio', verbose_name='Composition file')),
                ('composition_date', models.DateField(auto_now_add=True, null=True, verbose_name='Song release date')),
            ],
        ),
        migrations.RemoveField(
            model_name='album',
            name='envelope',
        ),
        migrations.RemoveField(
            model_name='album',
            name='title',
        ),
        migrations.RemoveField(
            model_name='album',
            name='user',
        ),
        migrations.RemoveField(
            model_name='playlists',
            name='envelope',
        ),
        migrations.RemoveField(
            model_name='playlists',
            name='song',
        ),
        migrations.RemoveField(
            model_name='playlists',
            name='title',
        ),
        migrations.RemoveField(
            model_name='playlists',
            name='user',
        ),
        migrations.AddField(
            model_name='album',
            name='album_envelope',
            field=models.ImageField(null=True, upload_to='photo/%Y/%m/%d', verbose_name='Envelope'),
        ),
        migrations.AddField(
            model_name='album',
            name='album_title',
            field=models.CharField(blank=True, default='NoName', max_length=128, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='album',
            name='album_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Username'),
        ),
        migrations.AddField(
            model_name='playlists',
            name='playlist_envelope',
            field=models.ImageField(null=True, upload_to='photo/%Y/%m/%d', verbose_name='Envelope'),
        ),
        migrations.AddField(
            model_name='playlists',
            name='playlist_title',
            field=models.CharField(max_length=128, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='playlists',
            name='playlist_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='album',
            name='date_album',
            field=models.DateField(auto_now_add=True, verbose_name='Album release date'),
        ),
        migrations.AlterField(
            model_name='playlists',
            name='date_playlist',
            field=models.DateField(auto_now_add=True, verbose_name='Playlist creation date'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.TextField(blank=True, verbose_name='About'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date of birth'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=30, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(max_length=128, null=True, verbose_name='Singer nickname'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photo/%Y/%m/%d', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Username'),
        ),
        migrations.DeleteModel(
            name='Compozition',
        ),
        migrations.AddField(
            model_name='composition',
            name='composition_album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='musiccloud.album', verbose_name='Album'),
        ),
        migrations.AddField(
            model_name='composition',
            name='composition_singer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='musiccloud.profile', verbose_name='Singer'),
        ),
        migrations.AddField(
            model_name='composition',
            name='composition_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Username'),
        ),
        migrations.AddField(
            model_name='playlists',
            name='playlist_composition',
            field=models.ManyToManyField(blank=True, to='musiccloud.composition', verbose_name='Composition'),
        ),
    ]
