# Generated by Django 4.0.3 on 2022-04-15 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musiccloud', '0004_composition_remove_album_envelope_remove_album_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='composition',
            name='composition_playlist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='musiccloud.playlists', verbose_name='Playlist'),
        ),
        migrations.AlterField(
            model_name='composition',
            name='composition_title',
            field=models.CharField(blank=True, default='NoName', max_length=455, verbose_name='Title'),
        ),
    ]
