# Generated by Django 4.0.3 on 2022-04-15 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musiccloud', '0005_composition_composition_playlist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='composition',
            name='composition_playlist',
        ),
    ]
