# Generated by Django 4.0.3 on 2022-04-16 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musiccloud', '0006_remove_composition_composition_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_is_published',
            field=models.BooleanField(default=False, verbose_name='Released'),
        ),
        migrations.AddField(
            model_name='composition',
            name='composition_is_published',
            field=models.BooleanField(default=False, verbose_name='Released'),
        ),
    ]
