# Generated by Django 4.0.3 on 2022-04-16 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musiccloud', '0007_album_album_is_published_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='composition',
            options={'ordering': ['-composition_date']},
        ),
        migrations.AlterField(
            model_name='album',
            name='album_is_published',
            field=models.BooleanField(default=True, verbose_name='Released'),
        ),
        migrations.AlterField(
            model_name='album',
            name='date_album',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Album release date'),
        ),
        migrations.AlterField(
            model_name='composition',
            name='composition_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Song release date'),
        ),
        migrations.AlterField(
            model_name='composition',
            name='composition_is_published',
            field=models.BooleanField(default=True, verbose_name='Released'),
        ),
        migrations.AlterField(
            model_name='playlists',
            name='date_playlist',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Playlist creation date'),
        ),
    ]
